[workspace]
members = ["cargo:japan-dem-cli"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.5"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = [
  "shell",
  "powershell"
]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  # TODO: Currently, this is done by cross-compilation
  # "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  # TODO: link.exe fails with 1120 error. Some incompatibility with other C++ libraries...?
  # "x86_64-pc-windows-msvc"
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Use the bundled version of GDAL
features = ["bundled"]

[dist.dependencies.homebrew]


[dist.dependencies.apt]
sqlite3 = "*"

[dist.dependencies.chocolatey]
sqlite = "*"
